--SQL TO CREATE TABLE AND SET FK

-- user table
CREATE TABLE zonenone.USER (USER_ID INTEGER PRIMARY_KEY AUTO_INCREMENT, MAIL_ID VARCHAR(100), USER_NAME CARCHAR(50), PASSWORD VARCHAR(50));

--plan table
CREATE TABLE zonenone.PLAN(PLAN_ID INTEGER PRIMARY KEY AUTO_INCREMENT, PLAN_NAME VARCHAR(50), VOICE INTEGER, TEXT INTEGER, DATA VARCHAR(20), AMOUNT INTEGER, USER_ID INTEGER);

ALTER TABLE zonenone.PLAN ADD CONSTRAINT FK_USER_PLAN_ID FOREIGN KEY(USER_ID) REFERENCES zonenone.USER(USER_ID);

-- predicated_plan table
CREATE TABLE zonenone.PREDICATED_PLAN(ID INTEGER PRIMARY_KEY AUTO_INCREMENT, PLAN_ID INTEGER, USER_ID INTEGER, COUNT INTEGER, GENDER VARCHAR(10);)

ALTER TABLE zonenone.PREDICTAED_PLAN ADD CONSTRAINT FK_PLAN_ID FOREIGNN KEY(PLAN_ID) REFERENCES zonenone.PLAN(PLAN_ID);

ALTER TABLE zonenone.PREDICTAED_PLAN ADD CONSTRAINT FK_USER_ID FOREIGNN KEY(USER_ID) REFERENCES zonenone.USER(USER_ID);


insert into zonenone.user values(1, 'senthil.rethnasamy@verizon.com', 'senthil', 'senthil');
insert into zonenone.user values(2, 'roger.dhas@verizon.com', 'roger', 'roger');
insert into zonenone.user values(3, 'rajesh.ravi@verizon.com', 'rajesh', 'rajesh');

